//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDITIONAL_ROS
    {
        public decimal PERSON_ID { get; set; }
        public System.DateTime STARTD { get; set; }
        public System.DateTime TERMINATIOND { get; set; }
        public string MINE_CD { get; set; }
        public string OCCUPATION_CD { get; set; }
        public Nullable<decimal> DOC_ID { get; set; }
        public string ALTERNATE_SOURCE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DT { get; set; }
    }
}
