//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDITIONAL_SERVICE_PROOF
    {
        public decimal PROOF_SEQ { get; set; }
        public string PROOF_TYPE { get; set; }
        public Nullable<System.DateTime> FROM_D { get; set; }
        public Nullable<System.DateTime> TO_D { get; set; }
        public string MINE_NAME { get; set; }
        public string OTHER { get; set; }
        public Nullable<decimal> DOC_ID { get; set; }
        public decimal PERSON_ID { get; set; }
    }
}
