//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        public decimal ADDRESS_ID { get; set; }
        public decimal PERSON_ID { get; set; }
        public string ADDR_LINE_1 { get; set; }
        public string ADDR_LINE_2 { get; set; }
        public string ADDR_LINE_3 { get; set; }
        public string ADDR_LINE_4 { get; set; }
        public string ADDR_LINE_5 { get; set; }
        public string ADDR_LINE_6 { get; set; }
        public string ADDR_LINE_7 { get; set; }
        public string ADDR_LINE_8 { get; set; }
        public string ADDR_CODE { get; set; }
        public string NEAREST_CLINIC { get; set; }
        public string NEAREST_HOSPITAL { get; set; }
        public string ADDR_TYPE { get; set; }
        public string DEFAULT_ADDR { get; set; }
        public Nullable<System.DateTime> MODIFIED_DT { get; set; }
        public string FILE_REF { get; set; }
        public Nullable<decimal> TIMESTAMP { get; set; }
        public string SOURCE { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public string USER_INVALID { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public string CREATED_BY { get; set; }
        public string RSA_ADDRESS { get; set; }
        public string CITY_CD { get; set; }
        public string COUNTRY_CD { get; set; }
        public Nullable<double> ADDRESS_LATITUDE { get; set; }
        public Nullable<double> ADDRESS_LONGITUDE { get; set; }
        public string PROVINCE_CD { get; set; }
    }
}
