//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS_GEO
    {
        public string rsa_id_number { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string final_latitude { get; set; }
        public string final_longitude { get; set; }
        public string municipality_name { get; set; }
        public string province_code { get; set; }
        public string teba_office_name { get; set; }
        public decimal PERSON_ID { get; set; }
    }
}
