//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALIAS
    {
        public string IDDOCTYPECD { get; set; }
        public string IDDOCN { get; set; }
        public decimal PERSON_ID { get; set; }
        public string FILE_REF { get; set; }
        public Nullable<decimal> TIMESTAMP { get; set; }
        public string COUNTRY_OF_ISSUE { get; set; }
        public Nullable<System.DateTime> ISSUE_D { get; set; }
        public Nullable<System.DateTime> EXPIRY_D { get; set; }
        public decimal SCORE { get; set; }
        public string USER_INVALID { get; set; }
        public string SYSTEM_INVALID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DT { get; set; }
        public string PRIMARY_ID { get; set; }
        public string TEBA_CHECK { get; set; }
        public string CREATED_BY_USERGRP_CD { get; set; }
        public string MODIFIED_BY_USERGRP_CD { get; set; }
    }
}
