//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_MASTER
    {
        public decimal AUDIT_N { get; set; }
        public string USER_ID { get; set; }
        public string TXANTYPE_CD { get; set; }
        public Nullable<decimal> PERSON_ID { get; set; }
        public string CLAIM_ID { get; set; }
        public decimal TIMESTAMP { get; set; }
        public System.DateTime ACTUALD { get; set; }
        public Nullable<decimal> PACK_ID { get; set; }
        public Nullable<decimal> TXAN_UID { get; set; }
        public string SR_NUMBER { get; set; }
        public string USERGRP_CD { get; set; }
        public string TOKEN { get; set; }
    }
}
