//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_MASTER_DETAIL
    {
        public decimal AUDIT_N { get; set; }
        public string AUDITTABLECODE { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public decimal TIMESTAMP { get; set; }
    }
}
