//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_MASTER_LINKS
    {
        public decimal SEQ_N { get; set; }
        public decimal AUDIT_N { get; set; }
        public Nullable<decimal> PERSON_ID { get; set; }
        public Nullable<decimal> PACK_ID { get; set; }
        public string TABLE_NAME { get; set; }
        public System.DateTime ACTUAL_D { get; set; }
        public decimal TIMESTAMP { get; set; }
    }
}
