//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AURUM_FINDING
    {
        public long AURUM_DIAGNOSIS_ID { get; set; }
        public string ALGORITHM { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> VALUE { get; set; }
    }
}
