//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AURUM_DIAGNOSIS
    {
        public long AURUM_DIAGNOSIS_ID { get; set; }
        public Nullable<decimal> PERSON_ID { get; set; }
        public string STUDY_UID { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> DIAGNOSIS_DT { get; set; }
        public string STUDY_SERIES_UID { get; set; }
        public string PATIENT_ID { get; set; }
        public string archive { get; set; }
        public string INSTANCE_ID { get; set; }
        public string STATUS { get; set; }
    }
}
