//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_DETAILS
    {
        public decimal PERSON_ID { get; set; }
        public decimal BANK_SEQ_ID { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_CODE { get; set; }
        public string BANK_ACCOUNT_NUMBER { get; set; }
        public string BANK_ACCOUNT_HOLDER { get; set; }
        public string BANK_ACCOUNT_TYPE { get; set; }
        public Nullable<System.DateTime> LAST_KNOWN_D { get; set; }
        public Nullable<decimal> timestamp { get; set; }
        public string FILEREF { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFIED_BY { get; set; }
        public string BANK_ACCOUNT_OTHER { get; set; }
        public string USER_INVALID { get; set; }
        public Nullable<System.DateTime> MODIFIED_DT { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public string SRC { get; set; }
        public string BANK_ACCOUNT_HOLDER_INIT { get; set; }
    }
}
