//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_DETAILS_DOC
    {
        public decimal PERSON_ID { get; set; }
        public decimal BANK_SEQ_ID { get; set; }
        public decimal DOC_ID { get; set; }
    }
}
