//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BME_CATEGORY_OPTIONS
    {
        public string CATEGORY_ID { get; set; }
        public string OPTION_ID { get; set; }
        public string PROMPT { get; set; }
        public Nullable<decimal> OPTION_TYPE { get; set; }
        public string ENABLED { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public Nullable<decimal> COL_COUNT { get; set; }
        public Nullable<decimal> ROW_COUNT { get; set; }
        public string GROUP_ID { get; set; }
        public string LAYOUT_VERTICAL { get; set; }
    }
}
