//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BME_CATEGORY_ANSWERS
    {
        public string CATEGORY_ID { get; set; }
        public string OPTION_ID { get; set; }
        public string ANSWER_ID { get; set; }
        public string ANSWER_PROMPT { get; set; }
        public string ANSWER_VALUE { get; set; }
    }
}
