//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BME_ANSWERS
    {
        public decimal MEDICAL_ID { get; set; }
        public string CATEGORY_ID { get; set; }
        public string OPTION_ID { get; set; }
        public string ANSWER_ID { get; set; }
        public string ANSWER_VALUE { get; set; }
        public string ANSWER_COMMENT { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DT { get; set; }
        public Nullable<decimal> TIMESTAMP { get; set; }
    }
}
