//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CCMS_MasterEntities : DbContext
    {
        public CCMS_MasterEntities()
            : base("name=CCMS_MasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDITIONAL_ROS> ADDITIONAL_ROS { get; set; }
        public virtual DbSet<ADDITIONAL_SERVICE_PROOF> ADDITIONAL_SERVICE_PROOF { get; set; }
        public virtual DbSet<ADDRESS> ADDRESSes { get; set; }
        public virtual DbSet<ADDRESS_GEO> ADDRESS_GEO { get; set; }
        public virtual DbSet<ALIAS> Aliases { get; set; }
        public virtual DbSet<AUDIT_MASTER> AUDIT_MASTER { get; set; }
        public virtual DbSet<AUDIT_MASTER_DETAIL> AUDIT_MASTER_DETAIL { get; set; }
        public virtual DbSet<AUDIT_MASTER_LINKS> AUDIT_MASTER_LINKS { get; set; }
        public virtual DbSet<AURUM_DIAGNOSIS> AURUM_DIAGNOSIS { get; set; }
        public virtual DbSet<AURUM_FINDING> AURUM_FINDING { get; set; }
        public virtual DbSet<BANK_DETAILS> BANK_DETAILS { get; set; }
        public virtual DbSet<BANK_DETAILS_DOC> BANK_DETAILS_DOC { get; set; }
        public virtual DbSet<BME_ANSWERS> BME_ANSWERS { get; set; }
        public virtual DbSet<BME_CATEGORY_ANSWERS> BME_CATEGORY_ANSWERS { get; set; }
        public virtual DbSet<BME_CATEGORY_OPTIONS> BME_CATEGORY_OPTIONS { get; set; }
        public virtual DbSet<CALENDAR_DAYS> CALENDAR_DAYS { get; set; }
        public virtual DbSet<CCMS_CALL_DETAIL> CCMS_CALL_DETAIL { get; set; }
        public virtual DbSet<CCMS_CALLS> CCMS_CALLS { get; set; }
        public virtual DbSet<CCMS_RATES> CCMS_RATES { get; set; }
        public virtual DbSet<CERTIFICATION_ACK> CERTIFICATION_ACK { get; set; }
        public virtual DbSet<CERTIFICATION_SESSION_CERTIFICATIONS> CERTIFICATION_SESSION_CERTIFICATIONS { get; set; }
        public virtual DbSet<CERTIFICATION_SESSION_MEMBERS> CERTIFICATION_SESSION_MEMBERS { get; set; }
        public virtual DbSet<CERTIFICATION_SESSIONS> CERTIFICATION_SESSIONS { get; set; }
        public virtual DbSet<COL_CONVERSION> COL_CONVERSION { get; set; }
        public virtual DbSet<COL_DATA_GROUP> COL_DATA_GROUP { get; set; }
        public virtual DbSet<COL_VALIDATION> COL_VALIDATION { get; set; }
        public virtual DbSet<COMBINED_ROS> COMBINED_ROS { get; set; }
        public virtual DbSet<COMMUNICATION_GROUP_MAP> COMMUNICATION_GROUP_MAP { get; set; }
        public virtual DbSet<CONVERSATION_ITEM> CONVERSATION_ITEM { get; set; }
        public virtual DbSet<CPI> CPIs { get; set; }
        public virtual DbSet<LIST_DETAILS> LIST_DETAILS { get; set; }
        public virtual DbSet<LIST> LISTS { get; set; }
        public virtual DbSet<LM_ADDITIONAL_SERVICE_PROOF> LM_ADDITIONAL_SERVICE_PROOF { get; set; }
        public virtual DbSet<LM_ADDR_TYPE> LM_ADDR_TYPE { get; set; }
        public virtual DbSet<LM_AGENDA_STATUS> LM_AGENDA_STATUS { get; set; }
        public virtual DbSet<LM_AGENDA_TYPES> LM_AGENDA_TYPES { get; set; }
        public virtual DbSet<LM_ALL_ROS_NAMES> LM_ALL_ROS_NAMES { get; set; }
        public virtual DbSet<LM_APPLICATION_CHECK_LIST> LM_APPLICATION_CHECK_LIST { get; set; }
        public virtual DbSet<LM_APPLICATION_CHECK_LIST_HEADER> LM_APPLICATION_CHECK_LIST_HEADER { get; set; }
        public virtual DbSet<LM_AUDIT_FIELDS> LM_AUDIT_FIELDS { get; set; }
        public virtual DbSet<LM_AURUM_ARCHIVE> LM_AURUM_ARCHIVE { get; set; }
        public virtual DbSet<LM_BANK_ACCOUNT_TYPE> LM_BANK_ACCOUNT_TYPE { get; set; }
        public virtual DbSet<LM_BANK_NAME> LM_BANK_NAME { get; set; }
        public virtual DbSet<LM_BME_CATEGORIES> LM_BME_CATEGORIES { get; set; }
        public virtual DbSet<LM_BME_PAGE_NAMES> LM_BME_PAGE_NAMES { get; set; }
        public virtual DbSet<LM_CALL_STATUS> LM_CALL_STATUS { get; set; }
        public virtual DbSet<LM_CAPTURE_FIELDS> LM_CAPTURE_FIELDS { get; set; }
        public virtual DbSet<LM_CAUSE_OF_DEATH> LM_CAUSE_OF_DEATH { get; set; }
        public virtual DbSet<LM_CCMS_CALL_TYPES> LM_CCMS_CALL_TYPES { get; set; }
        public virtual DbSet<LM_CCMS_RATES> LM_CCMS_RATES { get; set; }
        public virtual DbSet<LM_CERTIFICATION_SESSION_STATUS> LM_CERTIFICATION_SESSION_STATUS { get; set; }
        public virtual DbSet<LM_CHECK_GROUPS> LM_CHECK_GROUPS { get; set; }
        public virtual DbSet<LM_CITY> LM_CITY { get; set; }
        public virtual DbSet<LM_CLAIMANT_ROLE> LM_CLAIMANT_ROLE { get; set; }
        public virtual DbSet<LM_CLAIMANT_TYPE> LM_CLAIMANT_TYPE { get; set; }
        public virtual DbSet<LM_COMMUNICATION> LM_COMMUNICATION { get; set; }
        public virtual DbSet<LM_COMMUNICATION_GROUP> LM_COMMUNICATION_GROUP { get; set; }
        public virtual DbSet<LM_COMPANIES> LM_COMPANIES { get; set; }
        public virtual DbSet<LM_CONVERSION> LM_CONVERSION { get; set; }
        public virtual DbSet<LM_COUNTRY> LM_COUNTRY { get; set; }
        public virtual DbSet<LM_DEFAULT_CONVERSATIONS> LM_DEFAULT_CONVERSATIONS { get; set; }
        public virtual DbSet<LM_DEFER_STATUS> LM_DEFER_STATUS { get; set; }
        public virtual DbSet<lm_doc_group_type> lm_doc_group_type { get; set; }
        public virtual DbSet<lm_doc_groups> lm_doc_groups { get; set; }
        public virtual DbSet<LM_DOC_TYPE> LM_DOC_TYPE { get; set; }
        public virtual DbSet<LM_DUTY> LM_DUTY { get; set; }
        public virtual DbSet<LM_EMAIL_TYPE> LM_EMAIL_TYPE { get; set; }
        public virtual DbSet<LM_EMP_STATUS> LM_EMP_STATUS { get; set; }
        public virtual DbSet<LM_ETHNIC_GROUP> LM_ETHNIC_GROUP { get; set; }
        public virtual DbSet<LM_EXIT_REASONS> LM_EXIT_REASONS { get; set; }
        public virtual DbSet<LM_FIELD_TYPE> LM_FIELD_TYPE { get; set; }
        public virtual DbSet<LM_FINGER> LM_FINGER { get; set; }
        public virtual DbSet<LM_FLAGS> LM_FLAGS { get; set; }
        public virtual DbSet<LM_FUND_NAME> LM_FUND_NAME { get; set; }
        public virtual DbSet<LM_FUND_TYPE> LM_FUND_TYPE { get; set; }
        public virtual DbSet<LM_GENDER> LM_GENDER { get; set; }
        public virtual DbSet<LM_IDDOCTYPECD> LM_IDDOCTYPECD { get; set; }
        public virtual DbSet<LM_ISSUE_AUTHORITY> LM_ISSUE_AUTHORITY { get; set; }
        public virtual DbSet<LM_ISSUE_TYPE> LM_ISSUE_TYPE { get; set; }
        public virtual DbSet<LM_LANGUAGE> LM_LANGUAGE { get; set; }
        public virtual DbSet<LM_LODGEMENT_BOOKING_STATUS> LM_LODGEMENT_BOOKING_STATUS { get; set; }
        public virtual DbSet<LM_LODGEMENT_BOOKING_TYPE> LM_LODGEMENT_BOOKING_TYPE { get; set; }
        public virtual DbSet<LM_LODGEMENT_SITE> LM_LODGEMENT_SITE { get; set; }
        public virtual DbSet<LM_LODGEMENT_SITE_GLOBAL_CONFIG> LM_LODGEMENT_SITE_GLOBAL_CONFIG { get; set; }
        public virtual DbSet<LM_LODGEMENT_SITE_TYPE> LM_LODGEMENT_SITE_TYPE { get; set; }
        public virtual DbSet<LM_LODGEMENT_TIMES> LM_LODGEMENT_TIMES { get; set; }
        public virtual DbSet<LM_LOOKUP_STRINGS> LM_LOOKUP_STRINGS { get; set; }
        public virtual DbSet<LM_MARITAL_STATUS> LM_MARITAL_STATUS { get; set; }
        public virtual DbSet<LM_MARKS> LM_MARKS { get; set; }
        public virtual DbSet<LM_MEDICAL_CONDITION> LM_MEDICAL_CONDITION { get; set; }
        public virtual DbSet<LM_MINE_LIST> LM_MINE_LIST { get; set; }
        public virtual DbSet<LM_MINE_ROS_NAMES> LM_MINE_ROS_NAMES { get; set; }
        public virtual DbSet<LM_MINELIST> LM_MINELIST { get; set; }
        public virtual DbSet<LM_MODIFIER_GROUPS> LM_MODIFIER_GROUPS { get; set; }
        public virtual DbSet<LM_OCCUPATION> LM_OCCUPATION { get; set; }
        public virtual DbSet<LM_OVERALL_RISK> LM_OVERALL_RISK { get; set; }
        public virtual DbSet<lm_pack_request_status> lm_pack_request_status { get; set; }
        public virtual DbSet<LM_PACK_STATUS_GROUP> LM_PACK_STATUS_GROUP { get; set; }
        public virtual DbSet<LM_PACK_TYPE> LM_PACK_TYPE { get; set; }
        public virtual DbSet<LM_PACSPROVIDERS> LM_PACSPROVIDERS { get; set; }
        public virtual DbSet<LM_PANEL_TYPE> LM_PANEL_TYPE { get; set; }
        public virtual DbSet<LM_PDLETTER_GROUP_CONTENTS> LM_PDLETTER_GROUP_CONTENTS { get; set; }
        public virtual DbSet<LM_PDLETTER_GROUPS> LM_PDLETTER_GROUPS { get; set; }
        public virtual DbSet<LM_PERSON_DOC_NOTICES_TYPE> LM_PERSON_DOC_NOTICES_TYPE { get; set; }
        public virtual DbSet<LM_PHONE_PROVIDERS> LM_PHONE_PROVIDERS { get; set; }
        public virtual DbSet<LM_PROVINCE> LM_PROVINCE { get; set; }
        public virtual DbSet<LM_QUALITY_OF_LIFE> LM_QUALITY_OF_LIFE { get; set; }
        public virtual DbSet<LM_REL_ROLE> LM_REL_ROLE { get; set; }
        public virtual DbSet<LM_REL_TYPE> LM_REL_TYPE { get; set; }
        public virtual DbSet<LM_REPORT_CATEGORIES> LM_REPORT_CATEGORIES { get; set; }
        public virtual DbSet<LM_REPORT_PARAM_TYPES> LM_REPORT_PARAM_TYPES { get; set; }
        public virtual DbSet<LM_RISK_AREA> LM_RISK_AREA { get; set; }
        public virtual DbSet<LM_RISK_INDICATOR> LM_RISK_INDICATOR { get; set; }
        public virtual DbSet<LM_RISKSCAPE_FINDINGS> LM_RISKSCAPE_FINDINGS { get; set; }
        public virtual DbSet<LM_RISKSCAPE_METADATA> LM_RISKSCAPE_METADATA { get; set; }
        public virtual DbSet<LM_ROS_ADDITIONAL_SOURCES> LM_ROS_ADDITIONAL_SOURCES { get; set; }
        public virtual DbSet<LM_SCAN_FAIL_REASON> LM_SCAN_FAIL_REASON { get; set; }
        public virtual DbSet<LM_SELF_DECLARED_RISK_INDICATOR> LM_SELF_DECLARED_RISK_INDICATOR { get; set; }
        public virtual DbSet<LM_SETTLEMENT_CLASSES> LM_SETTLEMENT_CLASSES { get; set; }
        public virtual DbSet<LM_SRC> LM_SRC { get; set; }
        public virtual DbSet<LM_SRC_SCORE> LM_SRC_SCORE { get; set; }
        public virtual DbSet<LM_STANDARD_NAMES> LM_STANDARD_NAMES { get; set; }
        public virtual DbSet<LM_SYSTEM_FUNCTIONS> LM_SYSTEM_FUNCTIONS { get; set; }
        public virtual DbSet<LM_SYSTEM_PAGES> LM_SYSTEM_PAGES { get; set; }
        public virtual DbSet<LM_SYSTEM_ROLES> LM_SYSTEM_ROLES { get; set; }
        public virtual DbSet<LM_TASK_TYPES> LM_TASK_TYPES { get; set; }
        public virtual DbSet<LM_TEBA_OFFICE> LM_TEBA_OFFICE { get; set; }
        public virtual DbSet<LM_TEBA_ROS_NAMES> LM_TEBA_ROS_NAMES { get; set; }
        public virtual DbSet<LM_TEL_TYPE> LM_TEL_TYPE { get; set; }
        public virtual DbSet<LM_TICKET_STATUS> LM_TICKET_STATUS { get; set; }
        public virtual DbSet<LM_TICKET_TYPE> LM_TICKET_TYPE { get; set; }
        public virtual DbSet<LM_TICKET_TYPE_RESPONSE> LM_TICKET_TYPE_RESPONSE { get; set; }
        public virtual DbSet<LM_TRUST_CERTIFICATIONS> LM_TRUST_CERTIFICATIONS { get; set; }
        public virtual DbSet<LM_TRUST_COMMITTEE_APPROVAL_TYPE> LM_TRUST_COMMITTEE_APPROVAL_TYPE { get; set; }
        public virtual DbSet<LM_TXAN_AUDIT_EVENT_TYPE> LM_TXAN_AUDIT_EVENT_TYPE { get; set; }
        public virtual DbSet<LM_USER_ROLES> LM_USER_ROLES { get; set; }
        public virtual DbSet<LM_VALIDATION> LM_VALIDATION { get; set; }
        public virtual DbSet<LM_VODACOM_ERROR_CODES> LM_VODACOM_ERROR_CODES { get; set; }
        public virtual DbSet<LOGIN_ATTEMPT> LOGIN_ATTEMPT { get; set; }
        public virtual DbSet<LOGIN_FAILURE> LOGIN_FAILURE { get; set; }
        public virtual DbSet<MEDICAL> MEDICALs { get; set; }
        public virtual DbSet<MEDICAL_CERT_PANEL> MEDICAL_CERT_PANEL { get; set; }
        public virtual DbSet<MEDICAL_CERT_PANEL_MEMBERS> MEDICAL_CERT_PANEL_MEMBERS { get; set; }
        public virtual DbSet<MENU_GROUP> MENU_GROUP { get; set; }
        public virtual DbSet<MENU_GROUP_ITEMS> MENU_GROUP_ITEMS { get; set; }
        public virtual DbSet<MENU_VALIDATIONS> MENU_VALIDATIONS { get; set; }
        public virtual DbSet<MENU> MENUS { get; set; }
        public virtual DbSet<MESSAGE_REQ> MESSAGE_REQ { get; set; }
        public virtual DbSet<USER_GROUP_ROLES> USER_GROUP_ROLES { get; set; }
        public virtual DbSet<USER_GROUP_SOURCE_PACKS> USER_GROUP_SOURCE_PACKS { get; set; }
        public virtual DbSet<USER_ROLES> USER_ROLES { get; set; }
        public virtual DbSet<USER_USER_GROUPS> USER_USER_GROUPS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<USERS_USER_PROFILES> USERS_USER_PROFILES { get; set; }
        public virtual DbSet<WEB_REGISTRATION> WEB_REGISTRATION { get; set; }
    }
}
