//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCMS_CALL_DETAIL
    {
        public decimal CALL_ID { get; set; }
        public decimal DETAIL_N { get; set; }
        public Nullable<decimal> DUPL_PERSON_ID { get; set; }
        public string DUPL_IDDOCN { get; set; }
        public string DUPL_IDDOCTYPECD { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DT { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public decimal TIMESTAMP { get; set; }
    }
}
