//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCMS_RATES
    {
        public string RATE_CD { get; set; }
        public System.DateTime ACTIVE_FROM_D { get; set; }
        public System.DateTime ACTIVE_TO_D { get; set; }
        public decimal RATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DT { get; set; }
        public Nullable<decimal> TIMESTAMP { get; set; }
        public string RATE_NAME { get; set; }
    }
}
