//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CCMSEntities : DbContext
    {
        public CCMSEntities()
            : base("name=CCMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Bureau> tbl_Bureau { get; set; }
        public virtual DbSet<tbl_Foreign_Identity_Number> tbl_Foreign_Identity_Number { get; set; }
        public virtual DbSet<tbl_Identity_Number> tbl_Identity_Number { get; set; }
        public virtual DbSet<tbl_Industry> tbl_Industry { get; set; }
        public virtual DbSet<tbl_Passport_Number> tbl_Passport_Number { get; set; }
        public virtual DbSet<tbl_Person> tbl_Person { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
    }
}
