//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCMS_CALLS
    {
        public decimal CALL_ID { get; set; }
        public string SUBMITTER { get; set; }
        public string TXAN_ID { get; set; }
        public Nullable<decimal> PERSON_ID { get; set; }
        public string CALL_TYPE { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DT { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public decimal TIMESTAMP { get; set; }
        public Nullable<decimal> PENDING_DOC { get; set; }
        public string COMMENTS { get; set; }
        public string CALL_STATUS { get; set; }
        public string SUBMITTER_USER_GRP_CD { get; set; }
        public Nullable<decimal> PACK_ID { get; set; }
        public string USER_CONTACT_NO { get; set; }
        public string USER_EMAIL_ADDR { get; set; }
        public Nullable<System.DateTime> FAILURE_D { get; set; }
        public string FAILURE_TIME { get; set; }
        public string SUBMISSION_KEY { get; set; }
    }
}
