//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICATION_SESSION_CERTIFICATIONS
    {
        public decimal SESSION_ID { get; set; }
        public decimal PACK_ID { get; set; }
        public string FINDING_KEY { get; set; }
        public string DEFER_KEY { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DT { get; set; }
        public Nullable<decimal> TIMESTAMP { get; set; }
        public string APPROVAL_KEY { get; set; }
    }
}
