//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICATION_SESSION_MEMBERS
    {
        public decimal SESSION_ID { get; set; }
        public decimal PERSON_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DT { get; set; }
        public Nullable<decimal> TIMESTAMP { get; set; }
        public string PRESENT { get; set; }
        public Nullable<System.DateTime> HEART_BEAT { get; set; }
        public string in_ROOM { get; set; }
    }
}
