//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMUNICATION_GROUP_MAP
    {
        public string COMMUNICATION_GROUP_CD { get; set; }
        public string COMMUNICATION_CD { get; set; }
        public decimal COMMUNICATION_ORDER { get; set; }
    }
}
