//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONVERSATION_ITEM
    {
        public decimal CONVERSATION_ITEM_ID { get; set; }
        public decimal TICKET_ID { get; set; }
        public string MESSAGE { get; set; }
        public System.DateTime TIMESTAMP { get; set; }
        public string SMS_SENT { get; set; }
        public decimal PERSON_ID { get; set; }
    }
}
