//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPI
    {
        public decimal cpi_id { get; set; }
        public System.DateTime CPI_MONTH { get; set; }
        public decimal CPI_INDEX { get; set; }
    }
}
