//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIST_DETAILS
    {
        public string LIST_NAME { get; set; }
        public decimal FILE_LINE { get; set; }
        public string INDUSTRY_NO { get; set; }
        public string ID_NO { get; set; }
        public string PASSPORT { get; set; }
        public string FOUND { get; set; }
        public Nullable<decimal> PERSON_ID { get; set; }
        public string LIST_DETAIL_STATUS { get; set; }
        public Nullable<decimal> PACK_ID { get; set; }
    }
}
