//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIST
    {
        public string LIST_NAME { get; set; }
        public Nullable<decimal> DOC_ID { get; set; }
        public string TEMPLATE_ID { get; set; }
        public string LIST_TYPE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<decimal> NUM_RECORDS { get; set; }
        public string PROCESS_STATUS { get; set; }
    }
}
