//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_APPLICATION_CHECK_LIST
    {
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string HEADER_CODE { get; set; }
        public string MANDATORY { get; set; }
        public string DECEASED { get; set; }
        public string USERGRP_CD { get; set; }
    }
}
