//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_AUDIT_FIELDS
    {
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string lookup_Name { get; set; }
        public string COL_NAME { get; set; }
    }
}
