//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_COUNTRY
    {
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string TEL_CODE { get; set; }
        public string SHOW_MOBILE_ONLY { get; set; }
        public Nullable<decimal> MIN_TEL_DIGITS { get; set; }
        public Nullable<decimal> MAX_TEL_DIGITS { get; set; }
        public string MOBILE_PREFIXES { get; set; }
        public string DROP_LEADING_ZERO { get; set; }
        public Nullable<int> HIGHLIGHT { get; set; }
        public string TEL_EXAMPLE { get; set; }
    }
}
