//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_CAPTURE_FIELDS
    {
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string FIELD_TYPE_CD { get; set; }
        public decimal MAX_LENGTH { get; set; }
        public string REGEX_VALIDATION { get; set; }
        public string LOOKUP_NAME { get; set; }
        public string VALIDATION_NAME { get; set; }
        public string SYSTEM_VALUE_NAME { get; set; }
    }
}
