//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lm_doc_groups
    {
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string SHORT_DESCRIPTION { get; set; }
        public string GROUP_TYPE { get; set; }
    }
}
