//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_ISSUE_AUTHORITY
    {
        public string code { get; set; }
        public string description { get; set; }
        public string country { get; set; }
        public string organization { get; set; }
        public string mine { get; set; }
        public Nullable<int> HIGHLIGHT { get; set; }
    }
}
