//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_LODGEMENT_SITE_GLOBAL_CONFIG
    {
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal OPERATING_HOURS { get; set; }
        public decimal NUM_OPERATORS { get; set; }
        public decimal OPERATOR_PROCESSING_MINUTES { get; set; }
        public decimal PRIORITY_SLOTS_PERCENT { get; set; }
        public decimal BOOKED_SLOTS_PERCENT { get; set; }
        public decimal BOOKING_HORIZON_MONTHS { get; set; }
        public decimal WAITING_LIST_SLOTS_PERCENT { get; set; }
    }
}
