//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_LODGEMENT_SITE
    {
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string CITY_CD { get; set; }
        public Nullable<decimal> OPERATING_HOURS { get; set; }
        public Nullable<decimal> NUM_OPERATORS { get; set; }
        public Nullable<decimal> OPERATOR_PROCESSING_MINUTES { get; set; }
        public Nullable<decimal> PRIORITY_SLOTS_PERCENT { get; set; }
        public Nullable<decimal> BOOKED_SLOTS_PERCENT { get; set; }
        public Nullable<decimal> BOOKING_HORIZON_MONTHS { get; set; }
        public Nullable<decimal> WAITING_LIST_SLOTS_PERCENT { get; set; }
        public string ADDR_LINE_1 { get; set; }
        public string ADDR_LINE_2 { get; set; }
        public string POSTAL_CODE { get; set; }
        public string IS_ACTIVE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_D { get; set; }
        public string SITE_TYPE_CD { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_END_D { get; set; }
    }
}
