//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_MODIFIER_GROUPS
    {
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string ALT_DESCRIPTION { get; set; }
        public string SUMMARY_GROUP { get; set; }
        public string SUMMARY_GROUP_DESC { get; set; }
        public string SCHEDULE_F { get; set; }
        public string TB_DCD { get; set; }
        public string SI_DCD { get; set; }
    }
}
