//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_OCCUPATION
    {
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string ON_BME_SCHEDULE { get; set; }
        public string OCCUPATION_RISK_INDICATOR_CODE { get; set; }
        public string IS_SELECTABLE { get; set; }
    }
}
