//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_OVERALL_RISK
    {
        public string OCCUPATION_RISK { get; set; }
        public string RISK_AREA { get; set; }
        public string RISK_SHIFTS_GT_0 { get; set; }
        public string OVERALL_RISK { get; set; }
    }
}
