//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_PACSPROVIDERS
    {
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string ISACTIVE { get; set; }
        public string ISLOCAL { get; set; }
        public string SEARCHABLE { get; set; }
        public string MODALITY { get; set; }
        public string INSTANCE { get; set; }
        public string PROXY_CMOVE_URL { get; set; }
        public string PATIENT_SEARCH_URL { get; set; }
        public string STUDIES_URL { get; set; }
        public string PREVIEW_URL { get; set; }
        public string SERIES_URL { get; set; }
        public string VIEWER_URL { get; set; }
        public string PATIENT_URL { get; set; }
        public string PDF_URL { get; set; }
        public string INSTANCE_URL { get; set; }
        public string PASSWORD { get; set; }
        public string USER_NAME { get; set; }
        public string DOWNLOAD_URL { get; set; }
        public string USE_AP_SEARCH { get; set; }
    }
}
