//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_PANEL_TYPE
    {
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal MIN_MEMBERS { get; set; }
        public decimal MAX_MEMBERS { get; set; }
        public string DUTY_CD { get; set; }
        public string DOCUMENT_DESCRIPTION { get; set; }
        public string CHAIRMAN_DESC { get; set; }
    }
}
