//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_PHONE_PROVIDERS
    {
        public string PREFIX_NUMBER { get; set; }
        public string PHONE_PROVIDER_TYPE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string SERVICE_PROVIDER { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
