//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_REPORT_PARAM_TYPES
    {
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string RENDER_TYPE { get; set; }
        public string SQL { get; set; }
        public string LOOKUP_NAME { get; set; }
    }
}
