//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_SRC
    {
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string COMBINED_ROS { get; set; }
        public string DERIVED_ROS { get; set; }
        public string SCHEDULEF_ROS { get; set; }
        public string TEBA_ROS { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public Nullable<bool> SPV_ROS { get; set; }
        public string DISPLAY_NAME { get; set; }
    }
}
