//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_SRC_SCORE
    {
        public string DATA_GROUP { get; set; }
        public string SRC { get; set; }
        public decimal NO_USER_NULL { get; set; }
        public decimal NO_USER_NOT_NULL { get; set; }
        public decimal NEW_USER_NULL { get; set; }
        public decimal NEW_USER_NOT_NULL { get; set; }
    }
}
