//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_TRUST_CERTIFICATIONS
    {
        public string code { get; set; }
        public string description { get; set; }
        public string Level2_lable { get; set; }
        public string Level1_lable { get; set; }
        public string description_long { get; set; }
        public string TCC_CERTIFICATE_DESCRIPTION { get; set; }
        public string TCC_CLAIMANT_TYPE { get; set; }
        public string TCC_ELIGIBLE_CLAIMANT_CLASS { get; set; }
        public string TCC_QUALIFYING_DISEASE { get; set; }
        public string TCC_QUALIFYING_DISEASE_DESCRIPTION { get; set; }
        public string IN_RELATION_TO { get; set; }
    }
}
