//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_TEBA_OFFICE
    {
        public string TEBA_OFFICE_CODE { get; set; }
        public string TEBA_OFFICE_NAME { get; set; }
        public string TEBA_REGION { get; set; }
        public Nullable<System.DateTime> TEBA_EXPIRY_DATE { get; set; }
    }
}
