//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LM_TEBA_ROS_NAMES
    {
        public string SITE_CD { get; set; }
        public string SITE_NAME { get; set; }
        public string STANDARD_NAME_CD { get; set; }
    }
}
