//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN_FAILURE
    {
        public decimal SEQ { get; set; }
        public string USER_ID { get; set; }
        public System.DateTime FAILURE_D { get; set; }
    }
}
