//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAL_CERT_PANEL
    {
        public decimal PANEL_ID { get; set; }
        public string PANEL_NAME { get; set; }
        public string IS_ACTIVE { get; set; }
        public string USER_GRP_CD { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DT { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public decimal TIMESTAMP { get; set; }
        public string PANEL_TYPE_CD { get; set; }
        public string MBOD_REDUCED { get; set; }
        public string INBOX_NAME { get; set; }
    }
}
