//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAL_CERT_PANEL_MEMBERS
    {
        public decimal PANEL_MEMBER_ID { get; set; }
        public decimal PANEL_ID { get; set; }
        public decimal PERSON_ID { get; set; }
        public string IS_DELETED { get; set; }
        public string MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DT { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public decimal TIMESTAMP { get; set; }
    }
}
