//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public string MENU_NAME { get; set; }
        public string MENU_DESCRIPTION { get; set; }
        public string ROUTE_STR { get; set; }
        public string ROUTE_PARAM { get; set; }
        public Nullable<decimal> sort_order { get; set; }
    }
}
