//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_VALIDATIONS
    {
        public string TXAN_ID { get; set; }
        public string PAGE_NUM { get; set; }
        public string VALIDATION_ID { get; set; }
        public decimal SEQ { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public string ERROR_SUGGESTION { get; set; }
        public string ERROR_RULE { get; set; }
        public string FIELD_NAME { get; set; }
        public string ERROR_LEVEL { get; set; }
        public string ENABLED { get; set; }
        public string STOP_ERROR { get; set; }
    }
}
