//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_GROUP_ITEMS
    {
        public string MENU_NAME { get; set; }
        public string GROUP_NAME { get; set; }
        public string SYSTEM_FUNCTION { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public string OVERIDE_DESC { get; set; }
        public string route_str { get; set; }
    }
}
