//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Person
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Surname { get; set; }
        public string Alternative_Surname { get; set; }
        public string Second_Name { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Gender { get; set; }
        public string Marital_Status { get; set; }
        public string Nationality { get; set; }
        public string Language_Preference { get; set; }
        public string Ethnic_Group { get; set; }
        public string Industry_Number { get; set; }
        public string Bureau_Number { get; set; }
        public string ID_No { get; set; }
        public string Passport { get; set; }
        public string Foreign_ID { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
