//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRUST_DETAIL
    {
        public int SRC_ID { get; set; }
        public string SRC_ADDRESS_TYPE { get; set; }
        public string SELECTED_COUNTRY { get; set; }
        public string SOURCE_LINE { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public string TOWN_NAME { get; set; }
        public string PROVINCE_CODE { get; set; }
        public string MUNICIPALITY_NAME { get; set; }
    }
}
