//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TRUST_DATAEntities : DbContext
    {
        public TRUST_DATAEntities()
            : base("name=TRUST_DATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TRUST_DETAIL> TRUST_DETAIL { get; set; }
    
        public virtual ObjectResult<Sp_TrustedData_Search_Info_Result> Sp_TrustedData_Search_Info(string searchKeyWord)
        {
            var searchKeyWordParameter = searchKeyWord != null ?
                new ObjectParameter("searchKeyWord", searchKeyWord) :
                new ObjectParameter("searchKeyWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_TrustedData_Search_Info_Result>("Sp_TrustedData_Search_Info", searchKeyWordParameter);
        }
    
        public virtual ObjectResult<Sp_Trusted_804_Data_Search_Info_Result> Sp_Trusted_804_Data_Search_Info(string searchKeyWord)
        {
            var searchKeyWordParameter = searchKeyWord != null ?
                new ObjectParameter("searchKeyWord", searchKeyWord) :
                new ObjectParameter("searchKeyWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Trusted_804_Data_Search_Info_Result>("Sp_Trusted_804_Data_Search_Info", searchKeyWordParameter);
        }
    }
}
