//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string COMPANY_CODE { get; set; }
        public string CURRPWD { get; set; }
        public string LOCKED { get; set; }
        public Nullable<System.DateTime> PWD_EXPIRY_DATE { get; set; }
        public Nullable<decimal> FAILED_COUNT { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN { get; set; }
        public Nullable<decimal> TIMESTAMP { get; set; }
        public Nullable<decimal> PERSON_ID { get; set; }
        public string DEFAULT_PAGE { get; set; }
        public string DEFAULT_USERGRP_CD { get; set; }
        public string USER_CONTACT_NO { get; set; }
        public string USER_EMAIL_ADDR { get; set; }
        public Nullable<decimal> PRIMARY_PROFILE { get; set; }
        public string START_TXAN_ROUTE_STR { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DT { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
    }
}
