//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_REGISTRATION
    {
        public decimal REG_ID { get; set; }
        public string SURNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string INDUSTRY_N { get; set; }
        public System.DateTime REG_D { get; set; }
        public string CONTACT_N { get; set; }
        public string REG_RESULT { get; set; }
        public string REG_MSG { get; set; }
        public Nullable<decimal> PERSON_ID { get; set; }
        public string CHANNEL { get; set; }
    }
}
